# Generated by Django 5.1.1 on 2025-02-24 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='buyer_eth_address',
            field=models.CharField(default=1, max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='eth_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='seller_eth_address',
            field=models.CharField(default=1, max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
