# Generated by Django 5.1.1 on 2025-02-25 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_credittransaction_buyer_eth_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_id',
            field=models.CharField(default='TXN-6d7cbc6c', editable=False, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_sold', models.IntegerField()),
                ('eth_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to='app.userprofile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_sales', to='app.userprofile')),
            ],
        ),
    ]
