# Generated by Django 5.1.1 on 2025-02-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_credittransaction_transaction_id_creditrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_id',
            field=models.CharField(default='TXN-d8e40b7d', editable=False, max_length=50, unique=True),
        ),
    ]
