# Generated by Django 5.1.1 on 2025-02-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_credittransaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditrequest',
            name='credits_sold',
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='request_date',
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='credits_requested',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests_buyer', to='app.userprofile'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests_seller', to='app.userprofile'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_id',
            field=models.CharField(default='TXN-54e4df30', editable=False, max_length=50, unique=True),
        ),
    ]
